pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                echo "Building for ${env.BRANCH_NAME}"
                // Common build steps
            }
        }
        
        stage('Test') {
                steps {                
                     docker.image('python:3.9-slim').inside {
                        echo "Running tests inside Docker container"
                        sh 'python3 -m unittest discover -s . -p "test_app.py" -v'
                    }
                }
            }
        }
        
        stage('Deploy') {
            when {
                branch 'main'
            steps {
                // Production deployment steps
                echo "Deploying, branch: ${env.BRANCH_NAME}"
            }
        }
    }
}